name: CD - Publicar no Docker Hub

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout do código
        uses: actions/checkout@v4

      
      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Definir nome e tag da imagem
        id: meta
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/checkpoint4" >> $GITHUB_OUTPUT
          echo "TAG=latest" >> $GITHUB_OUTPUT

      
      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
