name: CI - Build e Testes

on:
  push:
    branches:
      - develop
      - feature
      - hotfix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build e testes Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: 
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
          SPRING_JPA_SHOW_SQL: false
        run: mvn clean verify
