name: Release e Tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Gerar documentação
        run: mvn javadoc:javadoc

      - name: Criar Tag e Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.${{ github.run_number }}
          name: Release v1.${{ github.run_number }}
          body: "Release automática gerada pelo GitHub Actions"
